[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
optimizer = true
optimizer_runs = 200
solc = "0.8.26"
evm_version = "cancun"
via_ir = true
remappings = [
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@0glabs/0g-agent-nft/=lib/0g-agent-nft/",
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/"
]

[fmt]
line_length = 110
tab_width = 4
bracket_spacing = false
int_types = "long"

[rpc_endpoints]
zerog = "${ZEROG_RPC_URL}"

[etherscan]
zerog = { key = "any", url = "https://chainscan.0g.ai/api" }
